routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::namespace('Backend')->middleware('auth')->group(function(){
    Route::get('dashboard', 'DashboardController@index');
    Route::resource('product', 'ProductController');
    Route::resource('category', 'CategoryController');
});

Route::namespace('Frontend')->group(function(){
    Route::get('/', 'ProductController@index');
    Route::get('product/category/{id}', 'ProductController@byCategory')->name('product.category');
    Route::get('product.show/{id}', 'ProductController@show')->name('product.show');
});
// Route::get('/dashboard', 'Dashboard@index');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    
    protected $guarded = [];

    public function category(){
        return $this->belongsTo(Category::class);
    }

}

app/Http/Controllers/Api/ProductController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Product;
use App\Category;

class ProductController extends Controller
{
    public function index(){
        $products = Product::all();
        return response()->json(['products' => $products], 200);
    }

    public function show($id){
        $product = Product::with('category')->get()->find($id);
        return response()->json(['product' => $product], 200);
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::withCount('products')->get();
        return view('backend.category.index', ['categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category = Category::create($request->only(['name']));

        return redirect()->route('category.index', $category);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $category = Category::find($category);
        //  dd($category);
        return view('backend.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $category)
    {
        $category->update($request->only(['name']));
        return redirect()->route('backend.category.edit', $category);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Product;

class DashboardController extends Controller
{
    public function index(){
        $products = Product::all();
        return view('backend.dashboard', ['products' => $products]);
    }
}

app/Http/Controllers/Backend/ProductController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use App\Product;
use App\Category;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('backend.product.index', ['products' => $products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('backend.product.create', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->has('product_thumbnail')){
            $thumbnail_uploaded = $request->file('product_thumbnail');
            $thumbnail_name = time().".". $thumbnail_uploaded->getClientOriginalExtension();
            $thumbnail_path = public_path('/images');
            $thumbnail_uploaded->move($thumbnail_path, $thumbnail_name);
            $product = Product::create([
                'product_name'      => $request['product_name'],
                'product_content'   => $request['product_content'],
                'product_thumbnail' => '/images/'. $thumbnail_name,
                'category_id'       => $request['category_id'],
                'product_stock'       => $request['product_stock'],
            ]);
        }else{
            $product = Product::create([
                'product_name'      => $request['product_name'],
                'product_content'   => $request['product_content'],
                'category_id'       => $request['category_id'],
                'product_stock'       => $request['product_stock'],
            ]);
        }

        // $thumbnail = $request->file('product_thumbnail')->store('images');
        // $imageName = time().'.'.$request->file('product_thumbnail')->getClientOriginalExtension();  
        // $request->product_image->move(public_path('images'), $imageName);
        // // dd($request);
        // $product = Product::create($request->only(['product_name', 'product_content', 'product_thumbnail', 'category_id', 'product_stock']));

        return redirect()->route('product.edit', $product);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        echo "l";
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $product = Product::find($product);
        $categories = Category::all();
        // dd($product);
        return view('backend.product.edit', ['product' => $product, 'categories' => $categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        if($request->has('product_thumbnail')){
            $thumbnail_uploaded = $request->file('product_thumbnail');
            $thumbnail_name = time().".". $thumbnail_uploaded->getClientOriginalExtension();
            $thumbnail_path = public_path('/images');
            $thumbnail_uploaded->move($thumbnail_path, $thumbnail_name);
            $product->update([
                'product_name'      => $request['product_name'],
                'product_content'   => $request['product_content'],
                'product_thumbnail' => '/images/'. $thumbnail_name,
                'category_id'       => $request['category_id'],
                'product_stock'       => $request['product_stock'],
            ]);
        }else{
            $product->update([
                'product_name'      => $request['product_name'],
                'product_content'   => $request['product_content'],
                'category_id'       => $request['category_id'],
                'product_stock'     => $request['product_stock'],
            ]);
        }

        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
        return redirect()->route('product.index');
    }
}

app/Http/Controllers/Frontend/ProductController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Product;
use App\Category;

class ProductController extends Controller
{
    public function index(){
        $products = Product::all();
        $categories = Category::withCount('products')->get();
        return view('frontend.product.index', ['products' =>$products, 'categories' => $categories]);
    }

    public function byCategory($id){
        $products = Product::where('category_id', '=', $id)->get();
        // dd($products);
        $categories = Category::withCount('products')->get();
        return view('frontend.product.index', ['products' => $products, 'categories' => $categories]);
    }

    public function show($id){
        $product = Product::with('category')->get()->find($id);
        // dd($product);
        $categories = Category::withCount('products')->get();
        return view('frontend.product.show', ['product'=>$product, 'categories' => $categories]);
    }
}

resources/views/backend/product/create.blade.php
@extends('backend.layouts.backendapp')

@section('content')
<div class="col-9">
  <div class="content-wrapper py-3 border-bottom">
      <div class="content-head d-flex justify-content-between align-items-center mb-3">
        <h3 class="b-inline">Ürünler</h3>
        <a href="{{ route('product.index') }}" class="d-inline btn btn-success">Tüm Ürünler</a>
      </div>
      <div class="content">
        <form method="POST" action="{{ route('product.store') }}" enctype="multipart/form-data">
          @csrf
          <div class="form-row">
            <div class="form-group col-md-4">
              <label for="productName">Ürün Adı</label>
              <input type="text" name="product_name" class="form-control">
            </div>
            <div class="form-group col-md-4">
              <label for="productCategory">Ürün Kategorisi</label>
              <select id="productCategory" name="category_id" class="form-control">
                <option selected>Seç...</option>
                @foreach ($categories as $category)
                <option value="{{$category->id}}">{{$category->name}}</option>
                @endforeach
              </select>
            </div>
            <div class="form-group col-md-4">
              <label for="productStok">Stok</label>
              <input type="text" name="product_stock" class="form-control">
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="exampleFormControlTextarea1">Ürün Açıklaması</label>
              <textarea name="product_content" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
            <div class="form-group col-md-6">
              <label for="product_thumbnail">Ürün Resmi</label>
              <input name="product_thumbnail" type="file" class="form-control-file" id="product_thumbnail">
            </div>
          </div>
          <button type="submit" class="btn btn-primary">Kaydet</button>
        </form>
      </div>
  </div>
</div>
@endsection

resources/views/backend/product/edit.blade.php
@extends('backend.layouts.backendapp')

@section('content')
<div class="col-9">
  <div class="content-wrapper py-3 border-bottom">
      <div class="content-head d-flex justify-content-between align-items-center mb-3">
        <h3 class="b-inline">Ürünler</h3>
        <a href="{{ route('product.index') }}" class="d-inline btn btn-success">Tüm Ürünler</a>
      </div>
      <div class="content">
        <form method="POST" action="{{ route('product.update', $product[0]->id) }}" enctype="multipart/form-data">
          @csrf
          @method('PUT')
          <div class="form-row">
            <div class="form-group col-md-4">
              <label for="productName">Ürün Adı</label>
              <input type="text" name="product_name" class="form-control" value="{{ $product[0]->product_name }}">
            </div>
            <div class="form-group col-md-4"> 
              <label for="productCategory">Ürün Kategorisi</label>
              <select id="productCategory" name="category_id" class="form-control">
                <option value="{{$product[0]->category_id}}" selected>{{$product[0]->category->name}}</option>
                @foreach ($categories as $category)
                <option value="{{$category->id}}">{{$category->name}}</option>
                @endforeach
              </select>
            </div>
            <div class="form-group col-md-4">
              <label for="productStok">Stok</label>
              <input type="text" name="product_stock" class="form-control" value="{{ $product[0]->product_stock }}">
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="productContent">Ürün Açıklaması</label>
              <textarea name="product_content" class="form-control" id="productContent" rows="3">{{ $product[0]->product_content }}</textarea>
            </div>
            <div class="form-group col-md-6">
              <img src="{{url('/')}}{{$product[0]->product_thumbnail}}" alt="" style="display:block;">
              <label for="product_thumbnail">Ürün Resmi</label>
              <input name="product_thumbnail" type="file" class="form-control-file" id="product_thumbnail">
            </div>
          </div>
          <button type="submit" class="btn btn-primary">Kaydet</button>
        </form>
      </div>
  </div>
</div>
@endsection

resources/views/backend/product/index.blade.php
@extends('backend.layouts.backendapp')

@section('content')
<div class="col-9">
  <div class="content-wrapper py-3 border-bottom">
      <div class="content-head d-flex justify-content-between align-items-center mb-3">
        <h3 class="b-inline">Ürünler</h3>
        <a href="{{ route('product.create') }}" class="d-inline btn btn-success">Yeni Ekle</a>
      </div>
      <div class="content">
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Ürün Adı</th>
              <th scope="col">Ürün Kategori</th>
              <th scope="col">Stock</th>
              <th scope="col">İşlem</th>
            </tr>
          </thead>
          <tbody>
          @foreach ($products as $product)
            <tr>
              <th scope="row">{{$product->id}}</th>
              <td>{{$product->product_name}}</td>
              <td>{{$product->category->name}}</td>
              <td>{{$product->product_stock}}</td>
              <td>
                <a href="{{ route('product.edit', $product->id) }}"><i class="fas fa-edit fa-lg" style="color:green;margin-right:10px;"></i></a>
                <a href="#" 
                  onclick="var result=confirm('Silmek istediğinizden emin misiniz?');
                  if(result){
                    event.preventDefault();
                    document.getElementById('delete-form').submit();
                  }"
                  ><i class="fas fa-trash-alt fa-lg" style="color:red;"></i></a>
                <form id="delete-form" action="{{ route('product.destroy', $product->id) }}" method="POST" style="display:none;">
                  @csrf
                  <input type="hidden" name="_method" value="delete">
                </form>
              </td>
            </tr>
          @endforeach
          </tbody>
        </table>
      </div>
  </div>
</div>
@endsection